name = "Silly Modpack"
author = "Sillycat"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f92d488a89d56975b7fac32ddf0941221d050e6403a0465d7a1c74bed3e522d7"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
