name = "Silly Modpack"
author = "Sillycat"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eae8bd209b75f0f4bfd9c743b43fc5e0d54416a2b891278da5bbf67fa21d1218"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
