name = "Silly Modpack"
author = "Sillycat"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd1f9f0c16a1d3bc1af4998100041aa6b81ae73390183294ddbc617267102bff"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
