name = "Silly Modpack"
author = "Sillycat"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec02ad106cb5d6230ed735876f88411ea8fdca96b548131d0d283da41a257867"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
