name = "Silly Modpack"
author = "Sillycat"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecdcf992f9c6ca9a47dfbeced467201d80f36ff66695793a3c5b0921fbf44481"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
