name = "Silly Modpack"
author = "Sillycat"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60f7f5b4d52b552e2f98d0640d1fac73b5e37f908af261483e800a5475c82cb4"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
