name = "Silly Modpack"
author = "Sillycat"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6074f707259ac141436711489f14bdcb7f5ddf957e52122ed5968e2fb1b4e65"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
