name = "Silly Modpack"
author = "Sillycat"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c499e6fbfd7397329168ab10fb0c974201e6017ffe1c9bf0687d386851b476a1"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
